id: P600ABE3A
initial_creation_type: ocr
source_metadata:
  volumes:
    0b3e033cc6294421a23a36127e889483:
      base_file: v071.txt
      image_group_id: I1PD95916
      title: དབུས་དང་མཐའ་རྣམ་པར་འབྱེད་པའི་འགྲེལ་པ།
      total_pages: 1683
      volume_number: 71
